### ISSUE TITLE
watchdog chip (MAX6369KA) not needed

### ISSUE THREAD

**Issue by peterus** [Bambofy/FOSSASAT-1#12]
have seen that you are using a watchdog chip (MAX6369KA), but this chip is not needed as all AtMega's have a build in watchdog which can be used too and is doing exactly the same: resetting the chip if it is not responding anymore.

**Comment by juliantech5** [comment]
Unfortunately, this internal watchdog is not reliable and tolerant to SEU. It is recommendable to use an external watchdog. This specific unit has flight heritage on previous missions too.

**Comment by peterus** [comment]
thanks for the explanation! Did't know this fact :)
