### ISSUE TITLE
PDFs of PCB designs are not source code

### ISSUE THREAD

**Issue by Snowda** [Bambofy/FOSSASAT-1#2]
PDFs aren't even usable with manufacturers. That would require the gerber files.

But even then, the hardware is not currently open source without the original Altium/Kicad/Eagle/etc. files that can be modified or improved upon by outside individuals.

**Comment by marzoukali** [comment]
I was concerned about the same point, I want to make a big contribution there and i went through the whole code but i was wonder if we can create an easy integration test so we can solve the hardware closed source problem.

**Comment by juliantech5** [comment]
Hey all, excuse the delay. Been so busy getting the satellite built and tested that I have not had the chance to update. I will upload the gerber files of the last models and the latest source code soon.

**Comment by vinicentus** [comment]
Is there a timeline for this?

**Comment by juliantech5** [comment]
uploaded latest gerbers

**Comment by peterus** [comment]
wanted to check with JLCPCB if everything is here and what it would cost to order some PCBs with SMT components added to the PCBs. Looks like the Pick&Place File is missing. @juliantech5 can you please upload the file too? Thanks!
